[system]
compatible=Allwinner A333 HelperBoard
bootloader=custom
data-directory=/userdata/var/lib/rauc

[keyring]
path=/etc/rauc/ca.cert.pem
check-purpose=codesign

[handlers]
bootloader-custom-backend=/usr/lib/rauc/a333-bootloader.sh

[slot.rootfs.0]
device=/dev/mmcblk0p6
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p7
type=ext4
bootname=B

[slot.oem.0]
device=/dev/mmcblk0p8
type=ext4
parent=rootfs.0

[slot.oem.1]
device=/dev/mmcblk0p9
type=ext4
parent=rootfs.1

[slot.boot.0]
device=/dev/mmcblk0p4
type=raw
parent=rootfs.0

[slot.boot.1]
device=/dev/mmcblk0p5
type=raw
parent=rootfs.1
