#!/usr/bin/env bash
# Generate with Studio on the workstation; firmware builds use committed output.
set -euo pipefail
sdk_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
destination="$sdk_dir/oem/a333/src/media-panel"
action=${1:-generate}
project=${2:-"$destination/eez/lvgl-media-player.eez-project"}
usage() {
    echo "Usage: bash $0 {generate|import} [project.eez-project]"
    echo 'Set EEZ_STUDIO to the Studio executable or AppImage (0.29.0).'
    echo 'import copies output already generated by Studio; generate builds it first.'
}
case "$action" in
    -h|--help) usage; exit 0 ;;
    generate|import) ;;
    *) usage >&2; exit 2 ;;
esac
[[ $# -le 2 && -f $project ]] || { usage >&2; exit 2; }
project=$(realpath -- "$project")
generated=$(python3 - "$project" <<'PY'
import json, pathlib, sys
p = pathlib.Path(sys.argv[1])
data = json.loads(p.read_text())
general = data['settings']['general']
if not general.get('flowSupport') or general.get('lvglVersion') != '9.5.0':
    raise SystemExit('Expected an LVGL 9.5.0 project with EEZ Flow enabled')
build = data['settings']['build']
if not build.get('generateSourceCodeForEezFramework'):
    raise SystemExit('Enable Generate source code for EEZ framework in Studio')
print((p.parent / build['destinationFolder']).resolve())
PY
)
if [[ $action == generate ]]; then
    studio=${EEZ_STUDIO:-}
    [[ -n $studio && -x $studio ]] || {
        echo 'Set EEZ_STUDIO to an executable Studio 0.29.0 / AppImage.' >&2; exit 1;
    }
    studio=$(realpath -- "$studio")
    temporary=$(mktemp -d "${TMPDIR:-/tmp}/a333-eez.XXXXXXXX")
    # Retain isolated profile/log on failure for diagnosis. No live Studio profile.
    if [[ $studio == *.AppImage ]]; then
        (cd "$temporary" && "$studio" --appimage-extract >extract.log)
        studio="$temporary/squashfs-root/EEZ Studio"
    fi
    "$studio" --no-sandbox --disable-gpu --user-data-dir="$temporary/profile" \
        --build-project "$project" 2>&1 | tee "$temporary/build.log"
    # Studio 0.29 can exit 0 and print 'finished' even after generation errors.
    if ! grep -q 'No error and' "$temporary/build.log" ||
        grep -Eq '[1-9][0-9]* errors? .*detected|Error generating|Unhandled error' "$temporary/build.log"; then
        echo "EEZ generation failed; see $temporary/build.log" >&2; exit 1
    fi
fi
for file in ui.c ui.h screens.c screens.h actions.h vars.h eez-flow.cpp eez-flow.h images.c; do
    [[ -s $generated/$file ]] || { echo "Missing generated file: $generated/$file" >&2; exit 1; }
done
if grep -q 'undefinedget_var_' "$generated/ui.c"; then
    echo 'Studio native array bug: use a Flow global for wifi_networks, not a native array.' >&2
    exit 1
fi
mkdir -p "$destination/ui" "$destination/eez"
if [[ $generated != "$destination/ui" ]]; then
    cp -- "$generated/"*.c "$generated/"*.h "$generated/"*.cpp "$destination/ui/"
fi
if [[ $project != "$destination/eez/lvgl-media-player.eez-project" ]]; then
    cp -- "$project" "$destination/eez/lvgl-media-player.eez-project"
fi
echo "EEZ sources exported to $destination/ui"
echo 'Next: bash scripts/media-panel-dev.sh build media'
